#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
    This file is part of openastro.org.

    OpenAstro.org is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenAstro.org is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with OpenAstro.org.  If not, see <http://www.gnu.org/licenses/>.
"""

#basics
import sys, os.path, datetime, gettext

#copyfile
# from shutil import copyfile

# #pysqlite
# import sqlite3
# sqlite3.dbapi2.register_adapter(str, lambda s:s.decode('utf-8'))

# #template processing
# from string import Template

#minidom parser
from xml.dom.minidom import parseString

#GTK, cairo to display svg
# from gi import require_version
# require_version('Rsvg', '2.0')
# require_version('Gtk', '3.0')
# from gi.repository import Gtk, Gdk, GObject, Rsvg, cairo


#internal openastro modules
#sys.path.append("/usr/lib/python3.5/dist-packages") #trying to 'fix' some problems importing openastromod on some distros
#sys.path.append("/usr/lib/python3.5/site-packages") #trying to 'fix' some problems importing openastromod on some distros
from openastromod import zonetab, geoname, importfile, dignities, swiss as ephemeris, configuration, dtatbase, calculation_and_drawing

#debug
LOCAL=False
DEBUG=False
VERSION='2.0.0a'

#directories
if LOCAL:
	DATADIR=os.path.dirname(__file__)
elif os.path.exists(os.path.join(sys.prefix,'share','openastro.org')):
	DATADIR=os.path.join(sys.prefix,'share','openastro.org')
elif os.path.exists(os.path.join('usr','local','share','openastro.org')):
	DATADIR=os.path.join('usr','local','share','openastro.org')
elif os.path.exists(os.path.join('usr','share','openastro.org')):
	DATADIR=os.path.join('usr','share','openastro.org')
else:
	print("Exiting... can't find data directory")
	sys.exit()

#Translations
LANGUAGES_LABEL={
			"ar":"الْعَرَبيّة",
			"pt_BR":"Português brasileiro",
			"bg":"български език",
			"ca":"català",
			"cs":"čeština",
			"da":"dansk",
			"nl":"Nederlands",
			"eo":"Esperanto",
			"en":"English",
			"fi":"suomi",
			"fr":"Français",
			"de":"Deutsch",
			"el":"ελληνικά",
			"hu":"magyar nyelv",
			"it":"Italiano",
			"ja":"日本",
			"nds":"Plattdüütsch",
			"nb":"Bokmål",
			"pl":"język polski",
			"rom":"rromani ćhib",
			"ru":"Русский",
			"es":"Español",
			"sv":"svenska",
            "uk":"українська мова",
            "zh_TW":"正體字"
		}

TDomain = os.path.join(DATADIR,'locale')
LANGUAGES=list(LANGUAGES_LABEL.keys())
TRANSLATION={}
for i in range(len(LANGUAGES)):
	try:
		TRANSLATION[LANGUAGES[i]] = gettext.translation("openastro",TDomain,languages=[LANGUAGES[i]])
	except IOError as err:
		print("IOError! Invalid languages specified (%s) in %s" %(LANGUAGES[i],TDomain))
		TRANSLATION[LANGUAGES[i]] = gettext.translation("openastro",TDomain,languages=['en'])

try:
	TRANSLATION["default"] = gettext.translation("openastro",TDomain)
except IOError as err:
	print("OpenAstro.org has not yet been translated in your language! Could not load translation...")
	TRANSLATION["default"] = gettext.translation("openastro",TDomain,languages=['en'])

## class openAstroCfg moved to openastromod/configuration.py

#Sqlite database moved to openastromod/database.py

## calc and drawing moved to openastromod/calculation


##############
##############
#Main GTK Window moved to openastro/mainwindow.py


# Cairo svg class moved to openastro/drawsvg.py




#debug print function
def dprint(str):
	if "--debug" in sys.argv or DEBUG:
		print('%s' % str)

#gtk main

def main():
    Gtk.main()
    return 0

#start the whole bunch

if __name__ == "__main__":
	cfg = openAstroCfg()
	db = openAstroSqlite()
	openAstro = openAstroInstance()
	mainWindow()
	main()
